huahhuah/lovia-backend

app.js, controllers/users.js, docker-compose.yml, entities/Users.js, middlewares/auth.js, routes/users.js, utils/generateJWT.js, utils/validUtils.js
=> feat: 重構 auth 功能

Dockerfile, app.js, controllers/users.js, docker-compose.yml, package-lock.json, routes/users.js
Patch user profile 終於分拆後沒問題了，請幫確認，感謝
=> divided controller

app.js, controllers/projects.js, package-lock.json, package.json, routes/projects.js
API #10 完成提案，觀看完整募資資訊
GET - /api/v1/projects/{project_id}
=> Add get project API#10

controllers/users.js
- 新增 `GET /api/v1/users/profile` 會員個資查詢 API，可取得關聯的性別資料（relations: ["gender"]）
- 更新 `PATCH /api/v1/users/profile` 會員個資修改 API：
- 支援更新 `username`, `phone`, `avatar_url`, `birthday`, `gender`
- 性別欄位從下拉選單選擇後，會驗證 gender id 是否有效，若無效則回傳 400
- 透過前端畫面「編輯個人資料」功能進行測試
- 使用者可正常取得個資並更新性別欄位
- gender 的值需為資料庫中 Genders 表的 id
- 預設資料需先正確種入 genders 欄位（例如：男性、女性、其他、不願透露）
=> feat: 修改會員查詢與編輯 API

controllers/projects.js, controllers/users.js, package-lock.json, package.json, routes/projects.js
=> add update_project API#11

app.js, package-lock.json, package.json, routes/upload.js, services/uploadImg.js
=> upload_img_API#44

routes/upload.js, services/uploadImg.js
=> fix stroage issue and limit file size

controllers/projects.js, controllers/users.js, entities/Categories.js, entities/Projects.js, routes/projects.js, routes/upload.js, services/uploadImg.js, utils/validUtils.js
修改使用者名稱不能超過50個字元驗證
新增 首頁 整包排序 分類
新增  探索頁面
=> feat(api):新增探索API新增探索API

controllers/projects.js, entities/Project_progresses.js, routes/projects.js
=> get_progress_API#38

controllers/projects.js, db/data-source.js, entities/Project_comments.js, entities/Sponsorships.js, routes/projects.js, src/migrations/1747756007405-CreateProjectComments.ts
新增留言功能
修改  提案者名稱 顯示正確的project_team
修改 詳情 照片沒顯示分類圖
=> feat: 新增留言功能

controllers/projects.js, routes/upload.js
revise photo size from 2MB into 10MB
=> revise photo size

app.js, controllers/projects.js, cronJobs/cleanupPendingSponsorships.js, db/data-source.js, entities/InvoiceTypes.js, entities/Invoices.js, entities/Shippings.js, entities/Sponsorships.js, package.json, routes/projects.js, scripts/SeedInvoiceTypes.js, services/sponsorshipService.js, utils/validateInvoice.js
=> feat: 建立訂單功能

controllers/projects.js
API#10 add category to return data
API#11 add detail information to return data
=> add_category_to_return_data

controllers/projects.js, routes/projects.js
API#35 get project comment
API#37 get project faq
=> get_project_comment_API#35_&_get_project_faq_API#37

controllers/projects.js
only capture for useful information
=> revise_api35_capture_info

controllers/Admins.js, controllers/users.js, routes/admins.js, routes/users.js
Update the time and status, and if necessary, also update the role_id.
approved → proposer
rejected → member
=> add patch proposer status

app.js, controllers/linePay.js, controllers/newebpay.js, controllers/orders.js, controllers/projects.js, entities/InvoiceTypes.js, entities/Invoices.js, entities/Shippings.js, entities/Sponsorships.js, package-lock.json, routes/linePay.js, routes/orders.js, routes/payments.js, routes/projects.js, routes/webhooks.js, test.html, utils/mailer.js, utils/newebpay.js, utils/sendEmail.js, utils/sendInvoiceEmail.js, utils/sendSponsorSuccessEmail.js, verifyTradeInfo.js
- feat: 新增藍新金流 callback 功能
- 新增 /api/v1/webhooks/payment/callback 路由
- callback 成功後更新 sponsorship 狀態與寄出 email
- 尚未合併，需測試通過後再 merge
=> feat: NewebPay callback with sponsorship update and mail

controllers/Admins.js, controllers/users.js, routes/admins.js
=> remove_auth

app.js
=> feat: add Google OAuth route

routes/orders.js
=> 移除錯誤的router

controllers/projects.js
=> fix:修正建立訂單

controllers/linePay.js, services/projectService.js, services/sponsorshipService.js
修改linepay捐贈發票問題
調整歷年專案 增加緩衝 不讓今天直接顯示已結束
調整 未付款成功的訂單
=> fix:修改linepay捐贈發票問題

controllers/projects.js
fix: 儲存 faq 為 JSON.stringify(faq || [])，確保格式一致
=> fix: 儲存 faq 為 JSON.stringify(faq || [])，確保格式一致
